-- TABLE SPACE POUR LE NOUVEAU USER
<<<<<<< HEAD
CREATE TABLESPACE tbs_visualrs datafile 'C:\Users\gmarco\Documents\Louvois\oradata\basededonnees\tbs_visualrs.dbf' size 80M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
drop tablespace tbs_visualrs INCLUDING CONTENTS AND DATAFILES;

-- Tablesapce 
CREATE TABLESPACE TBS_COMPTEURS_RS datafile 'C:\Users\gmarco\Documents\Louvois\oradata\basededonnees\tbs_compteur_rs.dbf' size 80M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
CREATE TABLESPACE TBS_INDEX_COMPTEURS_RS datafile 'C:\Users\gmarco\Documents\Louvois\oradata\basededonnees\tbs_index_compteur_rs.dbf' size 80M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;
=======
--drop tablespace tbs_visualrs INCLUDING CONTENTS AND DATAFILES;
CREATE TABLESPACE tbs_visualrs datafile 'D:\app\neo\oradata\VISUALRS\tbs_visualrs.dbf' size 80M AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED EXTENT MANAGEMENT LOCAL AUTOALLOCATE SEGMENT SPACE MANAGEMENT AUTO;


grant connect,resource to DX ;
>>>>>>> 39c6af791356458bade8fbe54ef96ce0e9fab893

-- CREATION D'UN USER
CREATE USER DX 
    IDENTIFIED BY admin 
    DEFAULT TABLESPACE tbs_visualrs
    QUOTA 10M ON tbs_visualrs 
    TEMPORARY TABLESPACE temp
    PASSWORD EXPIRE;
    
grant connect,resource to DX ;
    
-- STATS sur les tables du DX
EXECUTE DBMS_STATS.GATHER_SCHEMA_STATS(ownname => 'DX');
